use DevDB;

CREATE TABLE IF NOT EXISTS Menu (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    isFullMenu BOOLEAN NOT NULL,
    thumbnailImage VARCHAR(255),
    fullPrice INTEGER NOT NULL,
    discountedPercent INTEGER,
    sold INTEGER NOT NULL,
    totalInStock INTEGER NOT NULL,
    largeImage VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DiscountedTimePeriod (
    id INTEGER NOT NULL,
    begin VARCHAR(255) NOT NULL,
    end VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Options (
    id INTEGER NOT NULL AUTO_INCREMENT,
    menuId INTEGER NOT NULL,
    label VARCHAR(255) NOT NULL,
    CONSTRAINT fk_menu FOREIGN KEY (menuId) REFERENCES Menu(id),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Choices (
    id INTEGER NOT NULL AUTO_INCREMENT,
    optionsId INTEGER NOT NULL,
    CONSTRAINT fk_options FOREIGN KEY (optionsId) REFERENCES Options(id),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Label (
    id INTEGER NOT NULL AUTO_INCREMENT,
    choiceId INTEGER,
    textLabel VARCHAR(255) NOT NULL,
    CONSTRAINT fk_choices FOREIGN KEY (choiceId) REFERENCES Choices(id),
    PRIMARY KEY (id)
);

